stars = [
    {
        "name": "Arcturus",
        "SAO": "100944",
        "ir_reading": -2.810,
        "v_reading": 0,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "4 Ari",
        "SAO": "143868",
        "ir_reading": 5.931,
        "v_reading": 5.841,
        "visible_times_mst": ["unsure yet"],
    },

    {
        "name": "HD 15385",
        "SAO": "75398",
        "ir_reading": 5.921,
        "v_reading": 6.190,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 26676",
        "SAO": "93821",
        "ir_reading": 6.042,
        "v_reading": 6.249,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 4772",
        "SAO": "166608",
        "ir_reading": 5.919,
        "v_reading": 6.30,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 1667",
        "SAO": "166201",
        "ir_reading": 6.060,
        "v_reading": 6.75,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "V* KK And",
        "SAO": "54788",
        "ir_reading": 5.995,
        "v_reading": 5.91,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 8710",
        "SAO": "37214",
        "ir_reading": 6.032,
        "v_reading": 6.89,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "V* VV Ari",
        "SAO": "74983",
        "ir_reading": 5.921,
        "v_reading": 6.70,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "* 5 Tri",
        "SAO": "55338",
        "ir_reading": 5.970,
        "v_reading": 6.23,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 27236",
        "SAO": "111729",
        "ir_reading": 6.078,
        "v_reading": 6.536,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 27742",
        "SAO": "76585",
        "ir_reading": 5.930,
        "v_reading": 5.986,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "* 62 Tau",
        "SAO": "76591",
        "ir_reading": 5.952,
        "v_reading": 6.337,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 27848",
        "SAO": "93913",
        "ir_reading": 5.935,
        "v_reading": 6.947,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 28114",
        "SAO": "111817",
        "ir_reading": 5.962,
        "v_reading": 6.055,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 29819",
        "SAO": "111989",
        "ir_reading": 5.912,
        "v_reading": 6.74,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 31373",
        "SAO": "94212",
        "ir_reading": 5.942,
        "v_reading": 5.776,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "* 55 Eri B",
        "SAO": "131442",
        "ir_reading": 6.033,
        "v_reading": 6.73,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 31739",
        "SAO": "131640",
        "ir_reading": 6.078,
        "v_reading": 6.338,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 33224",
        "SAO": "131806",
        "ir_reading": 6.019,
        "v_reading": 5.78,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 32996",
        "SAO": "150149",
        "ir_reading": 6.047,
        "v_reading": 6.039,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 35007",
        "SAO": "132024",
        "ir_reading": 6.019,
        "v_reading": 5.68,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 37306",
        "SAO": "150617",
        "ir_reading": 5.992,
        "v_reading": 6.089,
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "Delta Capricorni",
        "SAO": "164644",
        "ir_reading": 2.063,        #Put Hband mag
        "v_reading": 2.83,          #Put Vband mag
        "visible_times_mst": ["unsure yet"],
    },
    {
        "name": "HD 172149",
        "SAO": "67171",
        "ir_reading": 8.01,             #Same as above
        "v_reading": 7.068,
        "visible_times_mst": ["unsure yet"],
    }
    # Add more stars as needed
]
